### ISSUE TITLE
Bug in gmm-gop.cc?

### ISSUE THREAD

**Issue by jcsilva** [jimbozhang/kaldi-gop#10]
Hi, 

I think there's a bug in gmm-gop.cc. You use KALDI_ASSERT several times in this file. But it's only evaluated when kaldi is compiled in Debug mode, as you may see in base/kaldi-error.h:
```
#ifndef NDEBUG
#define KALDI_ASSERT(cond) do { if (cond) (void)0; else \
   ::kaldi::KaldiAssertFailure_(__func__, __FILE__, __LINE__, #cond); } while(0)
#else
#define KALDI_ASSERT(cond) (void)0
#endif
```
If you compile it in release mode, KALDI_ASSERT doesn't do anything. So, the instructions in line 103 and 139 (`KALDI_ASSERT(ctx_dep_.Compute(phoneseq, c, &pdf_id));`) would not be executed and the code would not work as expected.

**Comment by jimbozhang** [comment]
Thank you very much. These bugs are stupid mistakes. I'll fix them soon.

------------------------------------------------------------------------------
张俊博
