### ISSUE TITLE
something wrong with local/compute-gmm-gop.sh line 16

### ISSUE THREAD

**Issue by hyuezhi** [jimbozhang/kaldi-gop#11]
when I completed the installation of kaldi-master, and run the run.sh, it turns out :

_local/compute-gmm-gop.sh: 34: /home/huyuezhi/wspace/kaldi-gop-master/egs/gop-compute/utils/parse_options.sh: Syntax error: Bad for loop variable_

is it because I installed the wrong version of kaldi?

I am new to GOP, please help me    : ) )

**Comment by hyuezhi** [comment]
I change the dash replace the bash , and solved the problem for now.

but I don't know if it has some further influence or not.

but thank your for the recipe——"gop-compute"   ：）

**Comment by annabelsu** [comment]
I also ran into this issue, and overcame it by replacing the shebang with "#!/bin/bash" in the "compute-gmm-gop.sh" file.

**Comment by amandeepbaberwal** [comment]
@annabelsu could you please explain it more how you did it? thanks
