### ISSUE TITLE
FST Issue in Compiling Binary

### ISSUE THREAD

**Issue by ziweizh** [jimbozhang/kaldi-gop#2]
![screen shot 2017-04-10 at 4 43 09 pm](https://cloud.githubusercontent.com/assets/18424299/24939592/2797b188-1f04-11e7-89ad-abc9aed029ec.png)

**Comment by petronny** [comment]
请提供你的kaldi下的openfst的版本

**Comment by jimbozhang** [comment]
The openfst version should be 1.6.2 (which do not include tr1/unordered_map in fst/util.h).
You need to update kaldi to the latest version.

**Comment by ziweizh** [comment]
Hello Junbo,

I have successfully ran the sample code using Ubuntu installed on Virtual
Box. I am wondering where the GOP scores are stored. Also, how can I apply
to my own data -- a set of nonnative English spontaneous speech recordings?

Thanks,
Ziwei
