### ISSUE TITLE
Using Language Model and Phone Decoder

### ISSUE THREAD

**Issue by yondu22** [jimbozhang/kaldi-gop#24]
Dan povey suggest use the phone decoder to get posterior probabilities, what do you think?
https://groups.google.com/d/msg/kaldi-help/4enr5jJrz3I/vKTopDolBAAJ
    
I am trying to implement GOP with Kaldi. The procedures I am taking are listed below:
    1) Force-align and use ali-to-phones to get phones 
    2) Use 2-gram phone decoder to get the phones and use lattice-to-post and post-to-phone-post to get the posterior prob of phones
    3) Use get-post-on-ali to obtain the prob of each phone at frame level, and average the prob of each phone from all of its corresponding frames.

    Does this make sense? I also found that the phones decoded from my 2-gram phone decoder don't make sense sometimes, not all the time. Actually I used the acoustic model trained from TED and built HCLG graph from 2-gram phones of TED speech materials, and use nnet3-latgen-faster to decode it. Should I use 3-gram instead?

Sounds reasonable.  I think you'll have to use a stronger LM; phones tend to be acoustically quite ambiguous so the
LM needs to be reasonable, to get anything accurate.
    

    Also I tried to implement GOP with another approach by calculating decodable.LogLikelihood(frame, tid) for each frame, and aggregated it, and the number doesn't look right. I don't know whether this approach makes sense or not.

    I have struggled over this for some time, and your time and help is well appreciated. 

log-likelihoods are quantities that, in general, won't even sum to one; and their values can be very different depending what type of model you have, whether you have a decision tree, the the prior, etc.  Getting something that makes sense is complicated.  If I were you I would focus on your first approach.

Dan 
Thanks,
Andy

What about implementing thins
```
## get the phone posterior per frame from the phone lattice

./lattice-to-post --acoustic-scale=0.1 ark:$data/phone_loop.lats ark,t:$data/1.post

./post-to-phone-post nnet3/final.mdl ark,t:$data/1.post ark,t:$result/phone.post





### get the best phone sequence from the phone lattice, and check the phone posterior on the best phone sequence



./ali-to-phones --per-frame=true nnet3/final.mdl ark:$data/phone_loop.1best.ali ark,t:$data/phone_loop_phones.tra

./get-post-on-ali ark:$result/phone.post ark:$data/phone_loop_phones.tra ark,t:$result/phone_loop_phones.conf
```

**Comment by jimbozhang** [comment]
I don't see the benefit of using LM. Have you compared the performance of your approach and the standard GOP?
