### ISSUE TITLE
compilation error: LIBLAPACK

### ISSUE THREAD

**Issue by zrsjta** [jimbozhang/kaldi-gop#27]
Hello!
when I try to build this project, an error occurs like this
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBLAPACK
    linked by target "gop" in directory /dockerdata/home/tyriontian/proj/server/kaldi-gop-master/src

-- Configuring incomplete, errors occurred!
See also "/dockerdata/home/tyriontian/proj/server/kaldi-gop-master/src/build/CMakeFiles/CMakeOutput.log".
See also "/dockerdata/home/tyriontian/proj/server/kaldi-gop-master/src/build/CMakeFiles/CMakeError.log".`

I have checked the CMakeLists and it seems that I do not have the file `liblapack_atlas.so.3`
But I do not know how to get this .so file. Actually I find some files with very similar name in /usr/lib64: `liblapack.so.3 `, for example. 

some information about my OS:
`Linux version 4.14.105-1-tlinux3-0010  (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)) #1 SMP Mon Aug 12 17:13:26 CST 2019`

I have install the ATLAS and LAPACK library by yum:
```
root@99e9f7a0-478f-484b-80d0-7a28d4eca8a6:/usr/lib64                                                                     
 yum install atlas                  
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package atlas-3.10.1-10.el7.x86_64 already installed and latest version
Nothing to do
(base) 
root@99e9f7a0-478f-484b-80d0-7a28d4eca8a6:/usr/lib64                                                                   
 yum install lapack                
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package lapack-3.4.2-5.el7.x86_64 already installed and latest version
Nothing to do
```

Thanks for your help! :)

**Comment by jimbozhang** [comment]
Try to install `atlas-devel` ？
