### ISSUE TITLE
Test Audio

### ISSUE THREAD

**Issue by ziweizh** [jimbozhang/kaldi-gop#3]
I am wondering how to use kaldi-gop for my own audio files (WAV). Thank you.

**Comment by jimbozhang** [comment]
This program only supports acoustic features. You have to extract them by yourself.

**Comment by ziweizh** [comment]
Hello Junbo,

By acoustic features, did you mainly refer to MFCC? I think kaldi requires
MFCC to be represented in a specific format. Do you mind referring to some
tutorials about representing acoustic features in Kaldi. Also, which lines
of codes in your kaldi-gop I should tweak in order to make it run on my own
acoustic feature data.

Thanks,
Ziwei
