### ISSUE TITLE
Running the example of the kaldi-gop ?

### ISSUE THREAD

**Issue by BilalDendani** [jimbozhang/kaldi-gop#33]
Hello, 
I successfully installed GMM-based GOP (Goodness of Pronunciation) using Kaldi. However, when running the example using :
`cd egs/gop-compute`
`./run.sh`

I got the following output: 

`~/kaldi-gop/egs/gop-compute$ ./run.sh`

local/compute-gmm-gop.sh --nj 1 --cmd run.pl data/eval data/lang exp/tri1 exp/eval_gop
local/compute-gmm-gop.sh: feature type is delta
local/compute-gmm-gop.sh: computing GOP in data/eval using model from exp/tri1, putting results in exp/eval_gop
bash: line 1:  2267 Aborted                 (core dumped) ( compute-gmm-gop exp/eval_gop/tree exp/eval_gop/final.mdl data/lang/L.fst "ark,s,cs:apply-cmvn  --utt2spk=ark:data/eval/split1/1/utt2spk scp:data/eval/split1/1/cmvn.scp scp:data/eval/split1/1/feats.scp ark:- | add-deltas  ark:- ark:- |" "ark:utils/sym2int.pl --map-oov 221 -f 2- data/lang/words.txt data/eval/split1/1/text|" ark,t:exp/eval_gop/gop.1 ) 2>> exp/eval_gop/log/gop.1.log >> exp/eval_gop/log/gop.1.log
run.pl: job failed, log is in exp/eval_gop/log/gop.1.log 

I am asking about the result. What is expected to get as a result?

**Comment by jimbozhang** [comment]
It looks like some input files of `compute-gmm-gop` were not correctly prepared.

Could you print some lines of the following files?

- data/eval/split1/1/utt2spk
- data/eval/split1/1/cmvn.scp
- data/eval/split1/1/feats.scp
- data/eval/split1/1/text

**Comment by BilalDendani** [comment]
Hello, 
Thank you for your quick answer. Find attached the 04 files in only one zip file.
[gmm-gop_Files.zip](https://github.com/jimbozhang/kaldi-gop/files/8620560/gmm-gop_Files.zip)

**Comment by BilalDendani** [comment]
I printed the last 05 lines for each file :

- data/eval/split1/1/utt2spk
 en_4156-B_039816-039947 en_4156-B
 en_4156-B_040104-040283 en_4156-B
 en_4156-B_040553-040622 en_4156-B
 en_4156-B_040699-040845 en_4156-B
 en_4156-B_040907-040966 en_4156-B

- data/eval/split1/1/cmvn.scp 
Only two lines in this file.
en_4156-A data/eval/cmvn.ark:10
en_4156-B data/eval/cmvn.ark:259

- data/eval/split1/1/feats.scp
en_4156-B_039816-039947 data/eval/raw_mfcc_eval2000.1.ark:278383
en_4156-B_040104-040283 data/eval/raw_mfcc_eval2000.1.ark:280469
en_4156-B_040553-040622 data/eval/raw_mfcc_eval2000.1.ark:283179
en_4156-B_040699-040845 data/eval/raw_mfcc_eval2000.1.ark:284459
en_4156-B_040907-040966 data/eval/raw_mfcc_eval2000.1.ark:286740
- data/eval/split1/1/text
en_4156-B_039816-039947 OH MY WELL SEE
en_4156-B_040104-040283 SO I HAVE NO MEN
en_4156-B_040553-040622 RANDY
en_4156-B_040699-040845 HE WENT MOVED TO TEXAS
en_4156-B_040907-040966 AND THEN HE

**Comment by amandeepbaberwal** [comment]
@BilalDendani hi Bilal, did you solve this problem?
