### ISSUE TITLE
can't successfully compiled，because there is no file in kaldi_root/src/thread/kaldi-thread.a

### ISSUE THREAD

**Issue by chijiaodaxie** [jimbozhang/kaldi-gop#4]
just like description in the title, details like:

`canning dependencies of target gop
Linking CXX static library libgop.a
[ 50%] Built target gop
Scanning dependencies of target compute-gmm-gop
make[2]: *** No rule to make target '/home/moma/Program_files/kaldi_no_share/src/thread/kaldi-thread.a', needed by 'compute-gmm-gop'.  Stop.
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/compute-gmm-gop.dir/all' failed
make[1]: *** [CMakeFiles/compute-gmm-gop.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2`

So, how to fix it?

**Comment by jimbozhang** [comment]
Fixed. And make sure use the branch 5.1 of Kaldi instead of its master branch.
