### ISSUE TITLE
Build error: No rule to make target kaldi-decoder.a'

### ISSUE THREAD

**Issue by panjunye** [jimbozhang/kaldi-gop#7]
Platform: macOS 10.12.6

[ 50%] Built target gop
make[2]: *** No rule to make target `../kaldi-5.1/src/decoder/kaldi-decoder.a', needed by `compute-gmm-gop'.  Stop.
make[1]: *** [CMakeFiles/compute-gmm-gop.dir/all] Error 2
make: *** [all] Error 2

**Comment by jimbozhang** [comment]
Have the dependency check (utils/check_dependencies.sh) passed? And is there any error occur when build src/kaldi-5.1?

**Comment by linkin627** [comment]
passed dependency check, but similar problem here:

Scanning dependencies of target compute-gmm-gop
[ 75%] Building CXX object CMakeFiles/compute-gmm-gop.dir/gopbin/compute-gmm-gop.cc.o
make[2]: *** No rule to make target '../kaldi-5.1/src/decoder/kaldi-decoder.a', needed by 'compute-gmm-gop'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/compute-gmm-gop.dir/all' failed
make[1]: *** [CMakeFiles/compute-gmm-gop.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by linkin627** [comment]
I fixed the same problem by first installed kaldi-5.1 successfully
