### ISSUE TITLE
Which models work?

### ISSUE THREAD

**Issue by bambamochu** [jimbozhang/kaldi-gop#8]
I tried to use the switchboard model, as well as fisher english, but got errors like this
WARNING (transform-feats[5.2.78~1392-af4b]:main():transform-feats.cc:110) Transform matrix for utterance utt has bad dimension 40x91 versus feat dim 117

however, voxforge from 
http://kaldi-asr.org/downloads/build/3/trunk/
works well

**Comment by jimbozhang** [comment]
It seems like the features mismatch. See https://github.com/jimbozhang/kaldi-gop/issues/9. If you can commit a recipe, it will be much appreciated.

**Comment by heqiqi** [comment]
Hi bamba518,
I am  a beginner of kaldi, and I run the author's model , met the " can not decode" issue. 
Could you share how you use Google with voxforge model? and how can I use my private .wav file?
Thanks a lot in advance.
